CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"actor_user_id" uuid,
	"event_type" text NOT NULL,
	"event_data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ip_address" "inet",
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "waitlist_approvals" (
	"email" text PRIMARY KEY NOT NULL,
	"approval_token" text DEFAULT encode(gen_random_bytes(24), 'base64') NOT NULL,
	"approved_at" timestamp with time zone,
	"approval_source" text NOT NULL,
	"approved_by" uuid,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "waitlist_approvals_approval_token_unique" UNIQUE("approval_token")
);
--> statement-breakpoint
ALTER TABLE "invites" ADD COLUMN "accepted_by" uuid;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_workspace_id_organizations_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_log_workspace_time" ON "audit_log" USING btree ("workspace_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_log_actor_time" ON "audit_log" USING btree ("actor_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_log_event_type" ON "audit_log" USING btree ("event_type","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "waitlist_pending" ON "waitlist_approvals" USING btree ("created_at" DESC NULLS LAST) WHERE approved_at IS NULL;
--> statement-breakpoint
-- ==========================================================================
-- Hand-augmented section (per user-flows-spec.md §4.1, §4.5, §4.6, §4.7)
-- Everything above was generated by drizzle-kit generate from db/schema/*.ts.
-- Everything below is manually authored raw SQL that Drizzle cannot express:
--   C.1: cross-schema FKs, RLS enablement, REVOKE, CHECK constraint
--   C.2: idempotent RPC replacements
--   C.3: workspace_members backfill + multi-owner collapse + invariants
-- ==========================================================================

--> statement-breakpoint
-- Cross-schema FKs to auth.users (Drizzle cannot express cross-schema FKs)
-- Per spec §4.5 (profiles, workspace_members) and inline on new columns
-- and new tables (invites.accepted_by §4.1.2, audit_log.actor_user_id §4.6,
-- waitlist_approvals.approved_by §4.7).
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_auth_users_id_fk" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_user_id_auth_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_accepted_by_auth_users_id_fk" FOREIGN KEY ("accepted_by") REFERENCES "auth"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_user_id_auth_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "auth"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "waitlist_approvals" ADD CONSTRAINT "waitlist_approvals_approved_by_auth_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "auth"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint

-- CHECK constraint on waitlist_approvals.approval_source (per spec §4.7).
-- Deferred from schema file because the CHECK syntax varies by Drizzle version
-- and we didn't want to bet on an unverified API surface.
ALTER TABLE "waitlist_approvals" ADD CONSTRAINT "waitlist_approvals_approval_source_check" CHECK ("approval_source" IN ('auto', 'manual', 'admin', 'campaign'));--> statement-breakpoint

-- Row-Level Security: enable on both new tables (per spec §4.6, §4.7).
-- Strategy: RLS on with zero policies. All app writes go through SECURITY
-- DEFINER RPCs (below in C.2) or service_role, both of which bypass RLS.
-- Comprehensive per-role policies (SELECT for admins, etc.) deferred to
-- Item 12 (docs/rls-audit.md execution) where the policy model is coherent.
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "waitlist_approvals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

-- Audit log append-only enforcement (per spec §4.6 "no UPDATE/DELETE to any
-- role including service_role in normal operation").
-- RLS alone does NOT block service_role (service_role bypasses RLS as owner).
-- REVOKE at the grant layer does. Keep INSERT and SELECT grantable.
-- FK set null on actor_user_id handles GDPR: when auth.users row is deleted,
-- audit_log preserves the entry with actor_user_id = NULL (anonymized).
REVOKE UPDATE, DELETE ON "audit_log" FROM PUBLIC, authenticated, anon, service_role;

--> statement-breakpoint
-- ==========================================================================
-- RPC replacements (per user-flows-spec.md §4.1.1, §4.1.2)
-- Return type matches existing RPCs (TABLE(org_id uuid, profile_created
-- boolean)). No DROP FUNCTION needed — CREATE OR REPLACE is sufficient.
-- ==========================================================================

--> statement-breakpoint
-- §4.1.1 — bootstrap_organization_membership (idempotent)
-- Idempotent via early-return + ON CONFLICT DO NOTHING heal path.
-- Creates: organization, profile (as lead), workspace_members (as owner),
-- audit_log entry (workspace.created). All in a single implicit transaction.
CREATE OR REPLACE FUNCTION public.bootstrap_organization_membership(
  target_user_id uuid,
  target_org_name text,
  target_org_slug text,
  target_full_name text,
  target_email text
)
RETURNS TABLE (org_id uuid, profile_created boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  existing_workspace_id uuid;
  created_org public.organizations;
BEGIN
  -- Idempotency guard: if profile already exists, return its workspace_id
  -- and heal any missing workspace_members row (partial-failure recovery)
  SELECT org_id INTO existing_workspace_id
  FROM public.profiles
  WHERE id = target_user_id;

  IF existing_workspace_id IS NOT NULL THEN
    INSERT INTO public.workspace_members (workspace_id, user_id, role, invited_by, created_at)
    VALUES (existing_workspace_id, target_user_id, 'owner'::public.workspace_role, NULL, now())
    ON CONFLICT (workspace_id, user_id) DO NOTHING;
    RETURN QUERY SELECT existing_workspace_id, false;
    RETURN;
  END IF;

  -- Fresh bootstrap path
  INSERT INTO public.organizations (name, slug)
  VALUES (target_org_name, target_org_slug)
  RETURNING * INTO created_org;

  INSERT INTO public.profiles (id, org_id, full_name, email, role)
  VALUES (target_user_id, created_org.id, target_full_name, target_email, 'lead'::public.role);

  INSERT INTO public.workspace_members (workspace_id, user_id, role, invited_by, created_at)
  VALUES (created_org.id, target_user_id, 'owner'::public.workspace_role, NULL, now());

  INSERT INTO public.audit_log (workspace_id, actor_user_id, event_type, event_data)
  VALUES (created_org.id, target_user_id, 'workspace.created',
    jsonb_build_object('workspace_name', target_org_name, 'slug', target_org_slug));

  RETURN QUERY SELECT created_org.id, true;
END;
$$;--> statement-breakpoint

-- §4.1.2 — accept_invite_membership (idempotent, new check order)
-- Check order (locked per spec line 240 + Pre-B1.b decision):
--   1. NOT FOUND on invite lookup    -> RAISE 'Invalid invite link'
--   2. expiry                         -> RAISE 'This invite has expired...'
--   3. email match                    -> RAISE 'This invite was sent to a
--                                              different email address'
--   4. idempotency (accepted_at)      -> early-return with sentinel if
--                                        acceptor isn't a member of the
--                                        invite's org (NULL::uuid signal)
-- Creates: profile if absent, workspace_members, audit_log entry
-- (member.joined). Updates: invites.accepted_at + invites.accepted_by.
-- Deferrals:
--   - project_members INSERT (needs invites.team_id from 0012/B2)
--   - workspace_members.role is hardcoded 'member'; mapping from
--     invites.role deferred to B2 per spec gap.
--   - audit_log event_data omits 'team_id' key; reinstate in 0012.
CREATE OR REPLACE FUNCTION public.accept_invite_membership(
  invite_token text,
  target_user_id uuid,
  target_full_name text,
  target_email text
)
RETURNS TABLE (org_id uuid, profile_created boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  invite_row public.invites%ROWTYPE;
  existing_profile public.profiles%ROWTYPE;
  created_profile boolean := false;
BEGIN
  -- 1. Invite lookup
  SELECT *
  INTO invite_row
  FROM public.invites
  WHERE token = invite_token
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid invite link';
  END IF;

  -- 2. Expiry check (moved above accepted_at check per spec line 240)
  IF now() > invite_row.expires_at THEN
    RAISE EXCEPTION 'This invite has expired. Ask your team lead to send a new one.';
  END IF;

  -- 3. Email match check
  IF lower(trim(target_email)) <> lower(trim(invite_row.email)) THEN
    RAISE EXCEPTION 'This invite was sent to a different email address';
  END IF;

  -- 4. Idempotency guard (accepted_at IS NOT NULL)
  -- If invite was already accepted, determine whether the caller is already
  -- a member of the invite's org:
  --   - Yes  -> success no-op: return the org_id (repeat click by the real
  --            acceptor, e.g. browser refresh)
  --   - No   -> return sentinel (NULL::uuid) so the caller can show a
  --            "this invite has already been used by someone else" UI
  --            without leaking which user consumed it
  IF invite_row.accepted_at IS NOT NULL THEN
    IF EXISTS (SELECT 1 FROM public.profiles
               WHERE id = target_user_id AND org_id = invite_row.org_id) THEN
      RETURN QUERY SELECT invite_row.org_id, false;
      RETURN;
    ELSE
      RETURN QUERY SELECT NULL::uuid, false;
      RETURN;
    END IF;
  END IF;

  -- Profile: create if absent (preserves existing cast invite_row.role::public.role)
  SELECT *
  INTO existing_profile
  FROM public.profiles
  WHERE id = target_user_id
  LIMIT 1;

  IF NOT FOUND THEN
    INSERT INTO public.profiles (id, org_id, full_name, email, role)
    VALUES (
      target_user_id,
      invite_row.org_id,
      target_full_name,
      target_email,
      invite_row.role::public.role
    );
    created_profile := true;
  END IF;

  -- workspace_members: hardcoded 'member' for invite-accepted joins.
  -- Intent-mapping from invites.role deferred to B2 (see roadmap parking lot
  -- 2026-04-22 "B2 workspace_members.role mapping").
  INSERT INTO public.workspace_members (workspace_id, user_id, role, invited_by, created_at)
  VALUES (
    invite_row.org_id,
    target_user_id,
    'member'::public.workspace_role,
    invite_row.invited_by,
    now()
  )
  ON CONFLICT (workspace_id, user_id) DO NOTHING;

  -- Path C: team-scoping INSERT into project_members deferred to migration
  -- 0012 (B2). invites.team_id and invites.team_role columns do not exist
  -- in 0011; the INSERT will be added when those columns land.

  -- Audit log (team_id key intentionally omitted; reinstate in 0012 per
  -- roadmap parking lot 2026-04-22 "0012 audit_log reinstate team_id")
  INSERT INTO public.audit_log (workspace_id, actor_user_id, event_type, event_data)
  VALUES (
    invite_row.org_id,
    target_user_id,
    'member.joined',
    jsonb_build_object(
      'invite_id', invite_row.id,
      'invited_by', invite_row.invited_by,
      'role', invite_row.role
    )
  );

  -- Mark invite accepted (both timestamp and acceptor-id)
  UPDATE public.invites
  SET accepted_at = now(),
      accepted_by = target_user_id
  WHERE id = invite_row.id;

  RETURN QUERY SELECT invite_row.org_id, created_profile;
END;
$$;

--> statement-breakpoint
-- ==========================================================================
-- Backfill + multi-owner collapse (per user-flows-spec.md §4.1.3)
-- Runs once at migration apply. Against lane dev (0 profiles, 0 rows) this
-- is a no-op. Against lane app at production apply time, it populates
-- workspace_members from the pre-0010 profiles table.
-- Invariants from spec lines 330-343 are asserted in STOP D pg-tap, not as
-- in-migration DO blocks (composition decision: avoid destructive
-- assertions during replay; see STOP C.2b discussion).
-- ==========================================================================

--> statement-breakpoint
-- Small-scale backfill (§4.1.3 single-query path). Preserves profiles.created_at
-- and maps profiles.role to workspace_role enum. Role mapping:
--   profiles.role IN ('lead','admin') -> workspace_members.role = 'owner'
--   all other profile roles           -> workspace_members.role = 'member'
-- Multi-owner cases (two profiles in the same org both mapping to 'owner')
-- are resolved by the collapse CTE below.
INSERT INTO public.workspace_members (workspace_id, user_id, role, invited_by, created_at)
SELECT
  p.org_id,
  p.id,
  CASE
    WHEN p.role IN ('lead', 'admin') THEN 'owner'::public.workspace_role
    ELSE 'member'::public.workspace_role
  END,
  NULL,
  p.created_at
FROM public.profiles p
LEFT JOIN public.workspace_members wm ON wm.user_id = p.id AND wm.workspace_id = p.org_id
WHERE wm.user_id IS NULL
ON CONFLICT (workspace_id, user_id) DO NOTHING;--> statement-breakpoint

-- Multi-owner collapse (§4.1.3). Partitions by workspace_id, ranks by
-- created_at ASC (earliest owner wins). Every rank > 1 is demoted from
-- 'owner' to 'admin'. Post-collapse, every workspace has exactly one owner
-- (the earliest-joined profile with role IN ('lead','admin')).
WITH ranked_owners AS (
  SELECT workspace_id, user_id, created_at,
    ROW_NUMBER() OVER (PARTITION BY workspace_id ORDER BY created_at ASC) AS rn
  FROM public.workspace_members
  WHERE role = 'owner'::public.workspace_role
)
UPDATE public.workspace_members
SET role = 'admin'::public.workspace_role
FROM ranked_owners
WHERE workspace_members.workspace_id = ranked_owners.workspace_id
  AND workspace_members.user_id = ranked_owners.user_id
  AND ranked_owners.rn > 1;
