"use client";

import { useState } from "react";

interface Digest {
  headline: string;
  shipped: string;
  attention: string;
  teamHealth: string;
  topAction: string;
}

export function DigestPanel() {
  const [digest, setDigest] = useState<Digest | null>(null);
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true);
    try {
      const res = await fetch("/api/digest");
      const data = await res.json();
      setDigest(data);
    } finally {
      setLoading(false);
    }
  }

  if (!digest && !loading) {
    return (
      <div className="border border-zinc-800 rounded-xl p-8 text-center">
        <p className="text-sm text-zinc-400 mb-1">AI reads your pipeline and writes the digest</p>
        <p className="text-xs text-zinc-600 mb-5">What shipped, what&apos;s stalled, what needs your attention</p>
        <button
          onClick={generate}
          className="bg-white text-zinc-900 rounded-lg px-4 py-2 text-sm font-medium hover:bg-zinc-100 transition-colors"
        >
          ✦ Generate digest
        </button>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="border border-zinc-800 rounded-xl p-8">
        <div className="flex items-center gap-3">
          <span className="w-4 h-4 border-2 border-zinc-700 border-t-indigo-400 rounded-full animate-spin" />
          <span className="text-sm text-zinc-500">Reading the pipeline…</span>
        </div>
      </div>
    );
  }

  if (!digest) return null;

  return (
    <div className="border border-zinc-800 rounded-xl overflow-hidden">
      {/* Top action — most prominent */}
      <div className="px-5 py-4 bg-indigo-500/5 border-b border-indigo-500/15">
        <p className="text-[10px] text-indigo-400 uppercase tracking-wide font-medium mb-1">✦ Top action today</p>
        <p className="text-sm text-zinc-200 font-medium">{digest.topAction}</p>
      </div>

      <div className="p-5 space-y-5">
        {/* Headline */}
        <p className="text-base text-white font-medium leading-snug">{digest.headline}</p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <DigestSection label="Shipped" text={digest.shipped} color="text-green-400" />
          <DigestSection label="Needs attention" text={digest.attention} color="text-yellow-400" />
          <DigestSection label="Team health" text={digest.teamHealth} color="text-blue-400" />
        </div>
      </div>

      <div className="border-t border-zinc-800 px-5 py-3 flex items-center justify-between">
        <span className="text-[10px] text-zinc-600">Generated by Claude · {new Date().toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })}</span>
        <button
          onClick={generate}
          className="text-xs text-zinc-500 hover:text-zinc-300 transition-colors"
        >
          Regenerate
        </button>
      </div>
    </div>
  );
}

function DigestSection({ label, text, color }: { label: string; text: string; color: string }) {
  return (
    <div>
      <p className={`text-[10px] uppercase tracking-wide font-medium mb-1.5 ${color}`}>{label}</p>
      <p className="text-sm text-zinc-400 leading-relaxed">{text}</p>
    </div>
  );
}
