"use client";

import { useState } from "react";
import type { WeeklyDigest, PmCoachingNote } from "@/lib/digest";

interface Props {
  initialDigest?: WeeklyDigest | null;
  onCoachingGenerated: (notes: PmCoachingNote[]) => void;
}

export function DigestPanel({ initialDigest, onCoachingGenerated }: Props) {
  const [digest, setDigest] = useState<WeeklyDigest | null>(initialDigest ?? null);
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true);
    try {
      const res = await fetch("/api/digest");
      const data: { digest: WeeklyDigest; pmCoaching: PmCoachingNote[] } = await res.json();
      setDigest(data.digest);
      onCoachingGenerated(data.pmCoaching);
    } finally {
      setLoading(false);
    }
  }

  if (!digest && !loading) {
    return (
      <div className="border rounded-xl p-8 text-center">
        <p className="text-sm text-muted-foreground mb-1">
          AI reads your pipeline and writes the digest
        </p>
        <p className="text-xs text-muted-foreground/60 mb-5">
          Shipped this week, cycle times, standout performers, coaching recommendations
        </p>
        <button
          onClick={generate}
          className="bg-primary text-primary-foreground rounded-lg px-4 py-2 text-sm font-medium transition-colors"
        >
          ✦ Generate digest
        </button>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="border rounded-xl p-8">
        <div className="flex items-center gap-3">
          <span className="w-4 h-4 border-2 border-border/80 border-t-primary rounded-full animate-spin" />
          <span className="text-sm text-muted-foreground">Reading the pipeline…</span>
        </div>
      </div>
    );
  }

  if (!digest) return null;

  return (
    <div className="border rounded-xl overflow-hidden">
      {/* Headline */}
      <div className="px-5 py-4 bg-primary/10 border-b border-primary/15">
        <p className="text-[10px] text-primary uppercase tracking-wide font-medium mb-1">
          ✦ Weekly design digest
        </p>
        <p className="text-sm text-foreground font-medium leading-snug">
          {digest.headline}
        </p>
      </div>

      <div className="divide-y divide-border">
        <div className="px-5 py-4">
          <p className="text-[10px] text-[#2E5339] uppercase tracking-wide font-medium mb-2">
            🚢 Shipped this week
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
            {digest.shippedThisWeek}
          </p>
        </div>

        <div className="px-5 py-4">
          <p className="text-[10px] text-muted-foreground uppercase tracking-wide font-medium mb-2">
            🧠 Team health
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">{digest.teamHealth}</p>
        </div>

        <div className="px-5 py-4">
          <p className="text-[10px] text-[#D4A84B] uppercase tracking-wide font-medium mb-2">
            ⭐ Standout
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">{digest.standout}</p>
        </div>

        <div className="px-5 py-4">
          <p className="text-[10px] text-amber-600 uppercase tracking-wide font-medium mb-2">
            💡 Recommendations
          </p>
          <ul className="space-y-1.5">
            {digest.recommendations.map((rec, i) => (
              <li
                key={i}
                className="text-sm text-muted-foreground leading-relaxed flex gap-2"
              >
                <span className="text-amber-500/60 shrink-0">{i + 1}.</span>
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="border-t px-5 py-3 flex items-center justify-between">
        <span className="text-[10px] text-muted-foreground/60">
          Generated by Claude ·{" "}
          {new Date().toLocaleDateString("en-US", {
            weekday: "long",
            month: "short",
            day: "numeric",
          })}
        </span>
        <button
          onClick={generate}
          className="text-xs text-muted-foreground hover:text-foreground transition-colors"
        >
          Regenerate
        </button>
      </div>
    </div>
  );
}
