#!/usr/bin/env tsx
/**
 * DB-access inventory.
 *
 * Scans the repo for imports of `@/db` (system role, bypasses RLS) and
 * `@/db/user` / `@/db/system`, categorizes each caller, and emits a
 * markdown table. Regenerates the table section in `docs/rls-audit.md`
 * when run with `--write`.
 *
 * Usage:
 *   npm run db:access-inventory              # print report to stdout
 *   npm run db:access-inventory -- --write   # rewrite the table in docs/rls-audit.md
 *
 * See Issue #43 for background.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

type Category = "system" | "user-scoped";

interface Entry {
  file: string;
  category: Category;
  imports: string[];
}

const SCRIPT_DIR = typeof __dirname !== "undefined"
  ? __dirname
  : fileURLToPath(new URL(".", import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, "..");
const DOCS_PATH = join(REPO_ROOT, "docs", "rls-audit.md");
const TABLE_MARKER_START = "<!-- db-access-inventory:start -->";
const TABLE_MARKER_END = "<!-- db-access-inventory:end -->";

// Directories to skip entirely. `docs/` is walked separately so .md references
// don't muddy the .ts/.tsx inventory.
const SKIP_DIRS = new Set([
  "node_modules",
  ".next",
  ".git",
  "dist",
  "build",
  ".vercel",
  "coverage",
  "playwright-report",
  "test-results",
]);

// Allowlisted paths from .eslintrc.json — these are legitimate system callers.
const ALLOWLIST_PATTERNS: RegExp[] = [
  /^app\/api\/cron\//,
  /^app\/views\//,
  /^lib\/ai\//,
  /^lib\/alerts\//,
  /^lib\/digest\.ts$/,
  /^lib\/figma\/sync\.ts$/,
  /^lib\/analytics\//,
  /^lib\/onboarding\//,
  /^lib\/dashboard\//,
  /^db\//,
  /^scripts\//,
];

const SYSTEM_IMPORT_PATTERNS = [
  /from\s+["']@\/db["']/,
  /from\s+["']@\/db\/system["']/,
];

const USER_IMPORT_PATTERNS = [/from\s+["']@\/db\/user["']/];

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    const s = statSync(full);
    if (s.isDirectory()) walk(full, acc);
    else if (/\.(ts|tsx|mjs)$/.test(name)) acc.push(full);
  }
  return acc;
}

function classify(fileAbs: string): Entry | null {
  const src = readFileSync(fileAbs, "utf8");
  const systemMatches = SYSTEM_IMPORT_PATTERNS.flatMap((re) => {
    const m = src.match(new RegExp(re.source, "g"));
    return m ?? [];
  });
  const userMatches = USER_IMPORT_PATTERNS.flatMap((re) => {
    const m = src.match(new RegExp(re.source, "g"));
    return m ?? [];
  });

  if (systemMatches.length === 0 && userMatches.length === 0) return null;

  const rel = relative(REPO_ROOT, fileAbs).split(sep).join("/");
  const imports = [...systemMatches, ...userMatches];

  // If a file imports both, classify as system (the stricter signal — it still
  // bypasses RLS for some queries). The imports column shows both.
  const category: Category = systemMatches.length > 0 ? "system" : "user-scoped";
  return { file: rel, category, imports };
}

function isAllowlisted(file: string): boolean {
  return ALLOWLIST_PATTERNS.some((re) => re.test(file));
}

function render(entries: Entry[]): string {
  const system = entries
    .filter((e) => e.category === "system")
    .sort((a, b) => a.file.localeCompare(b.file));
  const user = entries
    .filter((e) => e.category === "user-scoped")
    .sort((a, b) => a.file.localeCompare(b.file));

  const systemAllowed = system.filter((e) => isAllowlisted(e.file));
  const systemMigrate = system.filter((e) => !isAllowlisted(e.file));

  const lines: string[] = [];
  lines.push(
    `_Generated by \`npm run db:access-inventory\`. Do not edit by hand — re-run with \`--write\` to refresh._`
  );
  lines.push("");
  lines.push(`**Totals**`);
  lines.push("");
  lines.push(`| Category | Count |`);
  lines.push(`|---|---|`);
  lines.push(`| System (allowlisted) | ${systemAllowed.length} |`);
  lines.push(`| System (needs migration) | ${systemMigrate.length} |`);
  lines.push(`| User-scoped (\`@/db/user\`) | ${user.length} |`);
  lines.push(`| **Total callers** | **${entries.length}** |`);
  lines.push("");

  if (systemMigrate.length > 0) {
    lines.push(`### System callers — needs migration to \`withUserDb\` / \`withUserSession\``);
    lines.push("");
    lines.push(`| # | File |`);
    lines.push(`|---|---|`);
    systemMigrate.forEach((e, i) => lines.push(`| ${i + 1} | \`${e.file}\` |`));
    lines.push("");
  }

  if (systemAllowed.length > 0) {
    lines.push(`### System callers — allowlisted (legitimate system paths)`);
    lines.push("");
    lines.push(`| # | File |`);
    lines.push(`|---|---|`);
    systemAllowed.forEach((e, i) => lines.push(`| ${i + 1} | \`${e.file}\` |`));
    lines.push("");
  }

  if (user.length > 0) {
    lines.push(`### User-scoped callers`);
    lines.push("");
    lines.push(`| # | File |`);
    lines.push(`|---|---|`);
    user.forEach((e, i) => lines.push(`| ${i + 1} | \`${e.file}\` |`));
    lines.push("");
  }

  return lines.join("\n");
}

function writeToDocs(table: string): void {
  const src = readFileSync(DOCS_PATH, "utf8");
  const block = `${TABLE_MARKER_START}\n${table}\n${TABLE_MARKER_END}`;

  if (src.includes(TABLE_MARKER_START) && src.includes(TABLE_MARKER_END)) {
    const re = new RegExp(
      `${TABLE_MARKER_START}[\\s\\S]*?${TABLE_MARKER_END}`,
      "m"
    );
    writeFileSync(DOCS_PATH, src.replace(re, block));
  } else {
    // Append an inventory section at the end if markers don't exist yet.
    const appended =
      src.trimEnd() +
      "\n\n---\n\n## Automated inventory\n\n" +
      block +
      "\n";
    writeFileSync(DOCS_PATH, appended);
  }
}

function main(): void {
  const files = walk(REPO_ROOT);
  const entries = files
    .map(classify)
    .filter((e): e is Entry => e !== null);

  const table = render(entries);

  if (process.argv.includes("--write")) {
    writeToDocs(table);
    process.stdout.write(`Wrote inventory to ${relative(REPO_ROOT, DOCS_PATH)}\n`);
    return;
  }

  process.stdout.write(table + "\n");
}

main();
